// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOdLd8Z1SL-JG6Rww3G2XvLiUE1lodKh8',
    appId: '1:465234420780:web:b64d048ab83f7557df1d89',
    messagingSenderId: '465234420780',
    projectId: 'hospitaldemo-e602d',
    authDomain: 'hospitaldemo-e602d.firebaseapp.com',
    storageBucket: 'hospitaldemo-e602d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBleRQV4NgGGJCferlQ4XKPgrNoJGSa3-c',
    appId: '1:465234420780:android:ec750ab317a1a6b8df1d89',
    messagingSenderId: '465234420780',
    projectId: 'hospitaldemo-e602d',
    storageBucket: 'hospitaldemo-e602d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdPcSuQYeeFbXopacRb8GpMdew9osCmaw',
    appId: '1:465234420780:ios:c5457142414e4925df1d89',
    messagingSenderId: '465234420780',
    projectId: 'hospitaldemo-e602d',
    storageBucket: 'hospitaldemo-e602d.appspot.com',
    iosBundleId: 'com.example.blockchainDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdPcSuQYeeFbXopacRb8GpMdew9osCmaw',
    appId: '1:465234420780:ios:a6b285d911c92b8edf1d89',
    messagingSenderId: '465234420780',
    projectId: 'hospitaldemo-e602d',
    storageBucket: 'hospitaldemo-e602d.appspot.com',
    iosBundleId: 'com.example.blockchainDemo.RunnerTests',
  );
}
